language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm i

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "zhujinyao822"
  - git config user.email "425669746@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
# your branches
  only:
    - hexo

env:
 global:
   - GH_REF: github.com/zhujinyao822/zhujinyao822.github.io.git